// packages/webgl-chart-react/lib/chart.tsx
import React, { useRef, useEffect } from 'react';
import { GpuChart } from '@tomsoftware/webgl-chart';
import { ChartConfig } from './chart-config';

interface Props {
  data: ChartConfig;
  ariaLabel?: string;
  ariaDescribedBy?: string;
  onBind?: (element: HTMLElement | null) => void;
}

const Chart: React.FC<Props> = ({ data, ariaLabel, ariaDescribedBy, onBind}) => {
  const chartCanvasRef = useRef<HTMLCanvasElement>(null);
  const gpuChart = useRef<GpuChart | null>(null);

  useEffect(() => {
    const cav = chartCanvasRef.current;
    if (cav == null) {
      return;
    }

    console.debug('webgl-chart mounted');
    gpuChart.current = new GpuChart();
    gpuChart.current.bind(cav);
    gpuChart.current.setMaxFrameRate(data.maxFrameRate);
    gpuChart.current.setRenderCallback((context) => {
      if (data == null || data.onRender == null) {
        return;
      }
      data.onRender(context);
    });

    if (onBind) {
      onBind(cav);
    }

    gpuChart.current.render();

    return () => {
      if (gpuChart.current == null) {
        return;
      }
      console.debug('webgl-chart unmounted!');
      gpuChart.current.dispose();
    };
  }, [data]);


  useEffect(() => {
    if (gpuChart.current == null) {
      return;
    }
    gpuChart.current.setMaxFrameRate(data.maxFrameRate);
  }, [data.maxFrameRate]);

  return (
    <canvas
      ref={chartCanvasRef}
      role="img"
      aria-label={ariaLabel}
      aria-describedby={ariaDescribedBy}
    ></canvas>
  );
};

export default Chart;

// packages/webgl-chart-vue/chart.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUpdate, watch } from 'vue'
import { GpuChart } from '@tomsoftware/webgl-chart';
import { ChartConfig } from './chart-config';

const chartCanvas = ref<HTMLCanvasElement>();
const emit = defineEmits<{
  onBind: [element: HTMLElement]
}>();

const gpuChart = new GpuChart();

const props = defineProps<{
  data: ChartConfig
}>()

watch(
    () => props.data.maxFrameRate.value,
    (newValue) => {
      gpuChart.setMaxFrameRate(newValue);
    }
);


onMounted(() => {
  const cav = chartCanvas.value;
  if (cav == null) {
    return;
  }

  console.log('mounted', cav);

  gpuChart.bind(cav);
  gpuChart.setMaxFrameRate(props.data.maxFrameRate.value);
  gpuChart.setRenderCallback((context) => {
    if ((props.data == null) || ((props.data.onRender == null))) {
      return;
    }
    props.data.onRender(context)
  });

  emit('onBind', cav);

  gpuChart.render();
});

onBeforeUpdate(() => {
  console.log('unmounted');
});

</script>

<template>
  <div class="chart-container">
    <canvas ref="chartCanvas" class="chart-canvas"></canvas>
  </div>
</template>

<style scoped>

.chart-container {
  width:100%;
  height:100%;

  border: 1px solid red;

  position: relative;
}

.chart-canvas {
  width:100%;
  height:100%;

  border: 1px solid green;

  position: absolute;

}

</style>
