// packages/webgl-chart-react/src/chart.tsx
import React, { useRef, useEffect } from 'react';
import { GpuChart } from '@tomsoftware/webgl-chart';
import { ChartConfig } from './chart-config';

interface Props {
  data: ChartConfig;
  ariaLabel?: string;
  ariaDescribedby?: string;
  onBind?: (element: HTMLElement | null) => void;
}

const Chart: React.FC<Props> = ({ data, ariaLabel, ariaDescribedby, onBind}) => {
  const chartCanvasRef = useRef<HTMLCanvasElement>(null);
  const gpuChart = useRef<GpuChart | null>(null);

  useEffect(() => {
    const cav = chartCanvasRef.current;
    if (cav == null) {
      return;
    }

    console.debug('Chart component mounted to:', cav);
    gpuChart.current = new GpuChart();
    gpuChart.current.bind(cav);
    gpuChart.current.setMaxFrameRate(data.maxFrameRate);
    gpuChart.current.setRenderCallback((context) => {
      if (data == null || data.onRender == null) {
        return;
      }
      data.onRender(context);
    });

    if (onBind) {
      onBind(cav);
    }

    gpuChart.current.render();

    return () => {
      if (gpuChart.current == null) {
        return;
      }
      console.debug('Chart component unmounted!');
      gpuChart.current.dispose();
    };
  }, [data]);


  useEffect(() => {
    if (gpuChart.current == null) {
      return;
    }
    gpuChart.current.setMaxFrameRate(data.maxFrameRate);
  }, [data.maxFrameRate]);

  return (
    <canvas
      ref={chartCanvasRef}
      role="img"
      aria-label={ariaLabel}
      aria-describedby={ariaDescribedby}
    ></canvas>
  );
};

export default Chart;

// packages/webgl-chart-vue/lib/chart.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'
import { GpuChart } from '@tomsoftware/webgl-chart';
import { ChartConfig } from './chart-config';

interface Props {
  data: ChartConfig
  ariaLabel?: string;
  ariaDescribedBy?: string;
}

const props = defineProps<Props>();

const chartCanvas = ref<HTMLCanvasElement>();
const emit = defineEmits<{
  onBind: [element: HTMLElement]
}>();

const gpuChart = new GpuChart();

watch(
    () => props.data.maxFrameRate.value,
    (newValue) => {
      gpuChart.setMaxFrameRate(newValue);
    }
);

onMounted(() => {
  const cav = chartCanvas.value;
  if (cav == null) {
    return;
  }

  console.debug('webgl-chart mounted');

  gpuChart.bind(cav);
  gpuChart.setMaxFrameRate(props.data.maxFrameRate.value);
  gpuChart.setRenderCallback((context) => {
    if ((props.data == null) || ((props.data.onRender == null))) {
      return;
    }
    props.data.onRender(context)
  });

  emit('onBind', cav);

  gpuChart.render();
});

onBeforeUnmount(() => {
  console.debug('webgl-chart unmounted!');
  gpuChart.dispose();
});

</script>

<template>
  <canvas
    ref="chartCanvas"
    role="img"
    :aria-label="props.ariaLabel"
    :aria-describedby="props.ariaDescribedBy"
  ></canvas>
</template>
